server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
    }

    location ~* \.(html|js)$ {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location /img/ {
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
